apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: user-cleanup
  labels:
    app: user-cleanup
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-cleanup
      component: backend
  template:
    metadata:
      labels:
        app: user-cleanup
        component: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 5432; do echo "Waiting for PostgreSQL"; sleep 2; done']
      - name: run-migrations
        image: user-cleanup-backend:latest
        imagePullPolicy: Never
        command: ["python", "manage.py", "migrate"]
        env:
        - name: POSTGRES_DB
          value: "user_cleanup"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: django-secret-key
        - name: DEBUG
          value: "True"
      containers:
      - name: backend
        image: user-cleanup-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: "user_cleanup"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: INACTIVITY_THRESHOLD_DAYS
          value: "30"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: django-secret-key
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "localhost,127.0.0.1,backend"
        readinessProbe:
          httpGet:
            path: /admin/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /admin/
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: user-cleanup
  labels:
    app: user-cleanup
    component: backend
spec:
  selector:
    app: user-cleanup
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer